name: Tests / E2E Upgrade
on: 
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * *'

jobs:
  ibc-upgrade:
    uses: cosmos/ibc-go/.github/workflows/e2e-test-workflow-call.yml@main
    with:
      chain-image: ghcr.io/cosmos/ibc-go-simd
      chain-binary: simd
      chain-a-tag: v4.3.0
      chain-b-tag: v4.3.0
      # The chain A upgrade version
      chain-upgrade-tag: v5.1.0
      # The upgrade-plan-name must match the upgrade handler name registered and not be present in the starting tag
      # Example: https://github.com/cosmos/ibc-go/blob/v5.2.0/testing/simapp/app.go#L855-L860 
      upgrade-plan-name: "normal upgrade"
      test-entry-point:  "TestUpgradeTestSuite"
      # TestIBCChainUpgrade tests ibc transfer functionality before and after a chain upgrade
      test: "TestIBCChainUpgrade"

  regular-upgrade:
    uses: cosmos/ibc-go/.github/workflows/e2e-test-workflow-call.yml@main
    with:
      chain-image: damiannolan/sdk-simd
      chain-binary: simd
      chain-a-tag: v0.46.9
      chain-b-tag: v0.46.9
      # The chain A upgrade version
      chain-upgrade-tag: v0.47.0-dev
      # The upgrade-plan-name must match the upgrade handler name registered and not be present in the starting tag
      # Example: https://github.com/cosmos/cosmos-sdk/blob/release/v0.47.x/simapp/upgrades.go#L28
      upgrade-plan-name: "v046-to-v047"
      test-entry-point:  "TestUpgradeTestSuite"
      # TestChainUpgrade tests basic x/bank send functionality before and after a chain upgrade
      test: "TestChainUpgrade"